airbnb/lottie-spm

Package.swift, README.md
This PR updates the binary target to lottie-ios 4.1.1
=> Update binary target to lottie-ios 4.1.1

README.md, Sources/_LottieStub/Stub.swift
This PR removes `import Lottie` from the `_LottieStub` module. This wasn't actually necessary, it was just the first placeholder code that came to mind when I was setting it up. Removing this fixes issues where this package would fail to build in some circumstances: https://github.com/airbnb/lottie-spm/pull/5#issuecomment-1399216739, https://github.com/airbnb/lottie-ios/issues/1926#issuecomment-1398866563
=> Remove `import Lottie` from _LottieStub module 

Package.swift, README.md
This PR updates the binary target to lottie-ios 4.1.2
=> Update binary target to lottie-ios 4.1.2

.github/workflows/main.yml, Package.swift, README.md, Rakefile
This PR bumps the `Lottie.xcframework` pointer to [`lottie-ios` 4.1.3](https://github.com/airbnb/lottie-ios/releases/tag/4.1.3)
=> Bump XCFramework pointer to lottie-ios 4.1.3

Package.swift, README.md
This PR updates the XCFramework reference to lottie-ios `4.2.0`
=> Update XCFramework reference to lottie-ios 4.2.0

.github/workflows/main.yml, Package.swift, README.md, Rakefile
This PR updates the XCFramework reference in the `Package.swift` to point to lottie-ios 4.3.0: https://github.com/airbnb/lottie-ios/releases/tag/4.3.0
This PR also drops support for Swift 5.5, which we already did in the lottie-ios repo.
=> Update XCFramework reference to lottie-ios 4.3.0

Package.swift, README.md
This PR updates the XCFramework reference in `Package.swift` to the lottie-ios 4.3.1 release, and bumps the current version to 4.3.1.
=> Update XCFramework reference to lottie-ios 4.3.1

Package.swift, README.md
This PR updates the XCFramework reference in `Package.swift` to lottie-ios 4.3.2
=> Update XCFramework reference to lottie-ios 4.3.2

Package.swift, README.md
This PR updates the XCFramework reference to point to lottie-ios 4.3.3
=> Update XCFramework reference to lottie-ios 4.3.3

Package.swift, README.md
This PR updates the XCFramework in `Package.swift` to point to lottie-ios 4.3.4
=> Update XCFramework reference to lottie-ios 4.3.4

Package.swift, README.md
This PR updates the XCFramework reference in `Package.swift` to lottie-ios 4.4.0.
This properly completes support for visionOS, which was set up in https://github.com/airbnb/lottie-spm/pull/12 but was incomplete because the Lottie 4.3.4 XCFramework reference didn't support visionOS.
=> Update XCFramework reference to lottie-ios 4.4.0

.github/workflows/main.yml, Rakefile
GitHub released a new macOS 14 runner that uses Apple Silicon: https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/
This PR adopts the new macOS 14 runner. Since we now run our CI jobs on Apple Silicon, we no longer need the workaround for using the visionOS SDK on Intel.
=> Update CI jobs to run on Apple Silicon macOS 14 runner

PrivacyInfo.xcprivacy, README.md
This PR adds a copy of the lottie-ios privacy manifest to this repo.
The binary `Lottie.xcframework` includes a privacy manifest. In https://github.com/airbnb/lottie-ios/discussions/2364#discussioncomment-9007895, we've confirmed this is detected and consumed properly by Xcode. There's been some confusion about this though, since it's not obvious and not documented.
This PR documents how the privacy manifest integration works, and adds a copy of it to this repo for convenience. I also imported a few other relevant sections from lottie-ios's README.
=> Add Privacy Manifest

Package.swift, README.md
This PR updates the `Lottie.xcframework` reference in `Package.swift` to point to lottie-ios 4.4.2
=> Update Lottie.xcframework reference to lottie-ios 4.4.2

PrivacyInfo.xcprivacy
lottie-spm companion of lottie-ios PR: https://github.com/airbnb/lottie-ios/pull/2380
-----
Following the recommendation from airbnb/lottie-ios#2371, this updates the `NSPrivacyAccessedAPITypeReasons` in our privacy manifest from:
> [**3B52.1**](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api): Declare this reason to access the timestamps, size, or other metadata of files or directories that the user specifically granted access to, such as using a document picker view controller.
to:
> [**C617.1**](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api): Declare this reason to access the timestamps, size, or other metadata of files inside the app …
=> Update NSPrivacyAccessedAPITypeReasons in privacy manifest

Package.swift, README.md
This PR updates the XCFramework references in `Package.swift` to point to lottie-ios 4.4.3
=> Update XCFramework reference to lottie-ios 4.4.3

Package.swift, README.md
This PR removes the `#error("Linux is currently not supported")` error from our Package.swift.
This was originally so Swift Package Index wouldn't list this package as supporting Linux. This is causing issues for folks though, since it prevents the Package.manifest from being parsed on Linux (e.g. in CI): https://github.com/airbnb/lottie-ios/discussions/2328
Rather than having this workaround to fix the Swift Package Index badge, let's just remove both.
=> Remove Linux `#error` from Package.swift

.github/workflows/main.yml, Package.swift
This PR updates the Package.swift manifest to reference lottie-ios 4.5.0.
Lottie now only supports Xcode 15.0 / Swift 5.9 and later, so we can now simplify a few things in this repo as well.
=> Update Package.swift to reference lottie-ios 4.5.0

Package.swift, README.md
This PR updates the XCFramework reference in Package.swift to point to lottie-ios 4.5.1
=> Update to lottie-ios 4.5.1

README.md
Since the product name `Lottie` differs from the package name `lottie-spm` adding the dependency needs to specify the name of the product. This should be clarified in the readme.
=> Adds info about adding the dependency to the target
